# Root Hugo Configuration
baseURL = "https://anne-en-mathijs.pages.dev/"
title = "Anne & Mathijs"
languageCode = "nl-NL"
theme = "just-me"
timeZone = "Europe/Rome"

# Goldmark strips out any raw HTML this setting silences the corresponding warning
ignoreLogs = ["warning-goldmark-raw-html"]

[params]
  author = "Charlotte Boettjer"
  author_link = "https://linkedin.com/in/charlotte-boettjer-b545239a"
  #ga_tracking_id = "G-XXXXXXXXXX"  # Replace with your actual Google Tag ID

[[menu.main]]
    name = "RSVP"
    url = "/rsvp/"
    weight = 3
