# Root Hugo Configuration

#baseURL = "https://example.com" # Replace with production URL
title = "Anne & Mathijs"
theme = "just-me"
timeZone = "Europe/Rome"

# Goldmark strips out any raw HTML this setting silences the corresponding warning
ignoreLogs = ["warning-goldmark-raw-html"]
